/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.neilanthony;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nelly
 */
public class AbbeFileJPanel extends javax.swing.JPanel {

    public Params.FileParams fParams = new Params.FileParams();
    public LoadingRunnable loadingRunnable = new LoadingRunnable();
    public Thread loadingThread = new Thread(loadingRunnable);
    
    private final Color colorBkgdPanel = Color.getHSBColor(0.0f, 0.0f, 0.13f);
    private final Color colorBkgdMouseOver = Color.getHSBColor(0.0f, 0.0f, 0.15f);
    private final Color colorBkgdSelected = Color.getHSBColor(198f, 0.6f, 0.1f);
    
    /**
     * Creates new form AbbeFileJPanel
     */
    public AbbeFileJPanel(Params.FileParams fP) {
        initComponents();

        Dimension dim = new Dimension(198,97);
        //this.setPreferredSize(dim);
        //this.setSize(dim);
        this.setBounds(0, 0, 198, 97);
        
        this.fParams = fP;
        this.jLabel_Filename.setText(fP.fileName);
        this.jLabel_Filename.setForeground(Color.CYAN);
        this.jLabel_Loading.setForeground(Color.pink);
        this.setBackground(colorBkgdPanel);
        this.loadingThread.start();
    }
    
    public class LoadingRunnable implements Runnable {
        
        private int dotCount = 0;
        private int dotMax = 12;
        private double timeCounter = 0.0;
        private char[] dots = new char[dotMax];
        private String[] dotStrs = new String[dotMax];

//        {
//            for (char c : dots) { c = '.'; }
//        }
        
        private boolean stopThreadNow = false;
        public synchronized void stopThread() { this.stopThreadNow = true; }
        private synchronized boolean keepRunning() { return this.stopThreadNow == false; }
        
//        public LoadingRunnable() {
//            for (char c : dots) { c = '.'; }
//        }
        
        private void updateLoadingLabel () {
            double dotFraction;
            dotFraction = Math.round ( Math.abs(
                                Math.sin(timeCounter) * Double.valueOf(dotMax) ));
//            jLabel_Loading.setText(String.format("Loading%s",
//                    String.valueOf(Arrays.copyOfRange(dots, 0, (int)dotFraction))));
            jLabel_Loading.setText(String.format("Loading%s",dotStrs[((int)dotFraction)-1]));
            timeCounter += 0.2;
        }
        
        @Override
        public void run() {
            
            dotStrs[0] = "";
            dotStrs[1] = ".";
            dotStrs[2] = "..";
            dotStrs[3] = "...";
            dotStrs[4] = "....";
            dotStrs[5] = ".....";
            dotStrs[6] = "......";
            dotStrs[7] = ".......";
            dotStrs[8] = "........";
            dotStrs[9] = ".........";
            dotStrs[10] = "..........";
            dotStrs[11] = "...........";
           
            while (keepRunning()) {
                updateLoadingLabel();
                
                try { Thread.sleep(150);
                } catch (InterruptedException ex) {
                    Logger.getLogger(AbbeFileJPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Filename = new javax.swing.JLabel();
        jLabel_Loading = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(198, 97));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel_Filename.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel_Filename.setText("filenamegoeshere.obf");

        jLabel_Loading.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel_Loading.setText("Loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Filename)
                    .addComponent(jLabel_Loading))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Filename)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Loading)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Filename;
    private javax.swing.JLabel jLabel_Loading;
    // End of variables declaration//GEN-END:variables
}
