
package xyz.neilanthony;

import java.awt.Color;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class AbbeImageJPanel extends javax.swing.JPanel {

    private Color colorBkgdPanel = Color.getHSBColor(0.0f, 0.0f, 0.13f);
    private Color colorThumb = Color.getHSBColor(0.0f, 0.0f, 0.08f);
    private final Color colorChnText = Color.getHSBColor(0.54f, 0.46f, 0.66f);
    private Params.PanelParams p = null;
    private JLabel thumbLabel = null;
    private JPanel jPanel_Thumb = new JPanel();
    
    // Constructor
    public AbbeImageJPanel(Params.PanelParams params) throws IOException {
        initComponents();
        
        this.jPanel_PlaceHolder.setBackground(new Color(0,0,0,0));
        
        this.p = params;
        this.setBackground(colorBkgdPanel);
        
        //  create new panel
        jPanel_Thumb.setBounds(0, 0, p.psx, p.psy);
        if (this.p.bufImg != null) {
            JLabel picLabel = new JLabel(new ImageIcon(this.p.bufImg));
            picLabel.setBackground(colorThumb);
            jPanel_Thumb.add(picLabel);
            jPanel_Thumb.setBackground(colorThumb);
            this.jLabel_ChnName_1.setText(Integer.toString(p.bufImg.getWidth()));
            this.jLabel_ChnName_2.setText(Integer.toString(p.bufImg.getHeight()));
        } else {
            jPanel_Thumb.setBackground(colorThumb);
        }
        this.jLabel_ChnName_1.setForeground(colorChnText);
        this.jLabel_ChnName_2.setForeground(colorChnText);
        this.add(jPanel_Thumb);
        
        // update lables
        //this.jLabel_ImageName.setText(p.);
    }
    
    private JLabel chnLabel (String labelStr) {
        JLabel label = new JLabel(labelStr);
        //label.setFont(font);
        return label;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ImageName = new javax.swing.JLabel();
        jLabel_ChnName_1 = new javax.swing.JLabel();
        jLabel_ChnName_2 = new javax.swing.JLabel();
        jPanel_PlaceHolder = new javax.swing.JPanel();

        jLabel_ImageName.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel_ImageName.setText("Image Name Goes Here");

        jLabel_ChnName_1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel_ChnName_1.setText("CHN 1 NAME");

        jLabel_ChnName_2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel_ChnName_2.setText("CHN 2 NAME");

        javax.swing.GroupLayout jPanel_PlaceHolderLayout = new javax.swing.GroupLayout(jPanel_PlaceHolder);
        jPanel_PlaceHolder.setLayout(jPanel_PlaceHolderLayout);
        jPanel_PlaceHolderLayout.setHorizontalGroup(
            jPanel_PlaceHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        jPanel_PlaceHolderLayout.setVerticalGroup(
            jPanel_PlaceHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_PlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ImageName)
                    .addComponent(jLabel_ChnName_1)
                    .addComponent(jLabel_ChnName_2))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_PlaceHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_ImageName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ChnName_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_ChnName_2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_ChnName_1;
    private javax.swing.JLabel jLabel_ChnName_2;
    private javax.swing.JLabel jLabel_ImageName;
    private javax.swing.JPanel jPanel_PlaceHolder;
    // End of variables declaration//GEN-END:variables
}
